// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1lDZRKQSEMus0Y0IzW2mFMxX8427bf8',
    appId: '1:125896881539:web:5e6ced6fd55c8a0cecb2b6',
    messagingSenderId: '125896881539',
    projectId: 'learn-firebase-da8d3',
    authDomain: 'learn-firebase-da8d3.firebaseapp.com',
    storageBucket: 'learn-firebase-da8d3.firebasestorage.app',
    measurementId: 'G-94VF8FQX8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLrcKIAWfS9_aFuWdlYrRXcxyUDXJf-QI',
    appId: '1:125896881539:android:44418c39b4f715e5ecb2b6',
    messagingSenderId: '125896881539',
    projectId: 'learn-firebase-da8d3',
    storageBucket: 'learn-firebase-da8d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWirPqyG7kgDmUCZrdRYDuNYGegilEkM',
    appId: '1:125896881539:ios:c87686a3d36a185decb2b6',
    messagingSenderId: '125896881539',
    projectId: 'learn-firebase-da8d3',
    storageBucket: 'learn-firebase-da8d3.firebasestorage.app',
    iosBundleId: 'com.example.tasksFlutterFeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfWirPqyG7kgDmUCZrdRYDuNYGegilEkM',
    appId: '1:125896881539:ios:c87686a3d36a185decb2b6',
    messagingSenderId: '125896881539',
    projectId: 'learn-firebase-da8d3',
    storageBucket: 'learn-firebase-da8d3.firebasestorage.app',
    iosBundleId: 'com.example.tasksFlutterFeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq1lDZRKQSEMus0Y0IzW2mFMxX8427bf8',
    appId: '1:125896881539:web:70eab4876da41303ecb2b6',
    messagingSenderId: '125896881539',
    projectId: 'learn-firebase-da8d3',
    authDomain: 'learn-firebase-da8d3.firebaseapp.com',
    storageBucket: 'learn-firebase-da8d3.firebasestorage.app',
    measurementId: 'G-309CS50X6V',
  );

}